import { Providers } from "@/src/components/providers";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Gêmeos Barber Shop",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html suppressHydrationWarning lang="en">
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
